## -*- encoding: utf-8 -*-
## This file (t01-sequences.sagetex.sage) was *autogenerated* from t01-sequences.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('t01-sequences', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = 22
_st_.blockbegin()
try:
 var('n');
 a(n) = 3*n/(n^2+1);
except:
 _st_.goboom(25)
_st_.blockend()
_st_.current_tex_line = 30
_st_.blockbegin()
try:
 var('n');
 a(n) = 2^n/(2+2^n);
except:
 _st_.goboom(33)
_st_.blockend()
_st_.current_tex_line = 39
_st_.blockbegin()
try:
 var('n');
 a(n) = (-1)^n/(3*n);
except:
 _st_.goboom(42)
_st_.blockend()
_st_.current_tex_line = 48
_st_.blockbegin()
try:
 var('n');
 a(n) = (-1)^(n-1)/(2*n);
except:
 _st_.goboom(51)
_st_.blockend()
_st_.current_tex_line = 57
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==0 or n==1:
         return 1
     else:
         return a(n-1) + a(n-2);
except:
 _st_.goboom(64)
_st_.blockend()
_st_.current_tex_line = 70
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==1:
         return 3
     else:
         return a(n-1)/(n-1);
except:
 _st_.goboom(77)
_st_.blockend()
_st_.current_tex_line = 83
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==0:
         return 2
     else:
         return a(n-1)/(1+a(n-1));
except:
 _st_.goboom(90)
_st_.blockend()
_st_.current_tex_line = 96
_st_.blockbegin()
try:
 var('n');
 def a(n):
     return 3^n/factorial(2*n)
except:
 _st_.goboom(100)
_st_.blockend()
_st_.current_tex_line = 107
_st_.blockbegin()
try:
 var('n,m');
 a(n) = 3*n/(n^2+1);
except:
 _st_.goboom(110)
_st_.blockend()
_st_.current_tex_line = 114
_st_.blockbegin()
try:
 var('n,m');
 a(n) = 2^n/(2+2^n);
except:
 _st_.goboom(117)
_st_.blockend()
_st_.current_tex_line = 121
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^n/(3*n);
except:
 _st_.goboom(124)
_st_.blockend()
_st_.current_tex_line = 128
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^(n-1)/(2*n);
except:
 _st_.goboom(131)
_st_.blockend()
_st_.current_tex_line = 135
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^(n-1)/(2*n);
except:
 _st_.goboom(138)
_st_.blockend()
_st_.current_tex_line = 163
_st_.blockbegin()
try:
 var('n,m');
 a(n) = 3*n/(n^2+1);
except:
 _st_.goboom(166)
_st_.blockend()
_st_.current_tex_line = 170
_st_.blockbegin()
try:
 var('n,m');
 a(n) = 2^n/(2+2^n);
except:
 _st_.goboom(173)
_st_.blockend()
_st_.current_tex_line = 177
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^n/(3*n);
except:
 _st_.goboom(180)
_st_.blockend()
_st_.current_tex_line = 184
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^(n-1)/(2*n);
except:
 _st_.goboom(187)
_st_.blockend()
_st_.current_tex_line = 191
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==0 or n==1:
         return 1
     else:
         return a(n-1) + a(n-2);
except:
 _st_.goboom(198)
_st_.blockend()
_st_.current_tex_line = 203
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==1:
         return 3
     else:
         return a(n-1)/(n-1);
except:
 _st_.goboom(210)
_st_.blockend()
_st_.current_tex_line = 214
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==0:
         return 2
     else:
         return a(n-1)/(1+a(n-1));
except:
 _st_.goboom(221)
_st_.blockend()
_st_.current_tex_line = 225
_st_.blockbegin()
try:
 var('n');
 def a(n):
     return 3^n/factorial(2*n)
except:
 _st_.goboom(229)
_st_.blockend()
_st_.endofdoc()
