## -*- encoding: utf-8 -*-
## This file (t01-sequences-large.sagetex.sage) was *autogenerated* from t01-sequences-large.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('t01-sequences-large', version='2019/11/14 v3.4', version_check=True)
_st_.current_tex_line = 23
_st_.blockbegin()
try:
 var('n');
 a(n) = 3*n/(n^2+1);
except:
 _st_.goboom(26)
_st_.blockend()
_st_.current_tex_line = 31
_st_.blockbegin()
try:
 var('n');
 a(n) = 2^n/(2+2^n);
except:
 _st_.goboom(34)
_st_.blockend()
_st_.current_tex_line = 40
_st_.blockbegin()
try:
 var('n');
 a(n) = (-1)^n/(3*n);
except:
 _st_.goboom(43)
_st_.blockend()
_st_.current_tex_line = 49
_st_.blockbegin()
try:
 var('n');
 a(n) = (-1)^(n-1)/(2*n);
except:
 _st_.goboom(52)
_st_.blockend()
_st_.current_tex_line = 58
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==0 or n==1:
         return 1
     else:
         return a(n-1) + a(n-2);
except:
 _st_.goboom(65)
_st_.blockend()
_st_.current_tex_line = 71
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==1:
         return 3
     else:
         return a(n-1)/(n-1);
except:
 _st_.goboom(78)
_st_.blockend()
_st_.current_tex_line = 84
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==0:
         return 2
     else:
         return a(n-1)/(1+a(n-1));
except:
 _st_.goboom(91)
_st_.blockend()
_st_.current_tex_line = 97
_st_.blockbegin()
try:
 var('n');
 def a(n):
     return 3^n/factorial(2*n)
except:
 _st_.goboom(101)
_st_.blockend()
_st_.current_tex_line = 108
_st_.blockbegin()
try:
 var('n,m');
 a(n) = 3*n/(n^2+1);
except:
 _st_.goboom(111)
_st_.blockend()
_st_.current_tex_line = 115
_st_.blockbegin()
try:
 var('n,m');
 a(n) = 2^n/(2+2^n);
except:
 _st_.goboom(118)
_st_.blockend()
_st_.current_tex_line = 122
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^n/(3*n);
except:
 _st_.goboom(125)
_st_.blockend()
_st_.current_tex_line = 129
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^(n-1)/(2*n);
except:
 _st_.goboom(132)
_st_.blockend()
_st_.current_tex_line = 136
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^(n-1)/(2*n);
except:
 _st_.goboom(139)
_st_.blockend()
_st_.current_tex_line = 164
_st_.blockbegin()
try:
 var('n,m');
 a(n) = 3*n/(n^2+1);
except:
 _st_.goboom(167)
_st_.blockend()
_st_.current_tex_line = 171
_st_.blockbegin()
try:
 var('n,m');
 a(n) = 2^n/(2+2^n);
except:
 _st_.goboom(174)
_st_.blockend()
_st_.current_tex_line = 178
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^n/(3*n);
except:
 _st_.goboom(181)
_st_.blockend()
_st_.current_tex_line = 185
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^(n-1)/(2*n);
except:
 _st_.goboom(188)
_st_.blockend()
_st_.current_tex_line = 192
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==0 or n==1:
         return 1
     else:
         return a(n-1) + a(n-2);
except:
 _st_.goboom(199)
_st_.blockend()
_st_.current_tex_line = 204
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==1:
         return 3
     else:
         return a(n-1)/(n-1);
except:
 _st_.goboom(211)
_st_.blockend()
_st_.current_tex_line = 215
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==0:
         return 2
     else:
         return a(n-1)/(1+a(n-1));
except:
 _st_.goboom(222)
_st_.blockend()
_st_.current_tex_line = 226
_st_.blockbegin()
try:
 var('n');
 def a(n):
     return 3^n/factorial(2*n)
except:
 _st_.goboom(230)
_st_.blockend()
_st_.endofdoc()
