## -*- encoding: utf-8 -*-

# This file was *autogenerated* from the file t02-series.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9); _sage_const_8 = Integer(8); _sage_const_118 = Integer(118); _sage_const_45 = Integer(45); _sage_const_113 = Integer(113); _sage_const_10000 = Integer(10000); _sage_const_239 = Integer(239); _sage_const_232 = Integer(232); _sage_const_210 = Integer(210); _sage_const_216 = Integer(216); _sage_const_13 = Integer(13); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_10 = Integer(10); _sage_const_15 = Integer(15); _sage_const_14 = Integer(14); _sage_const_33 = Integer(33); _sage_const_35 = Integer(35); _sage_const_52 = Integer(52); _sage_const_109 = Integer(109); _sage_const_121 = Integer(121); _sage_const_127 = Integer(127); _sage_const_105 = Integer(105); _sage_const_1234 = Integer(1234); _sage_const_225 = Integer(225); _sage_const_249 = Integer(249)## This file (t02-series.sagetex.sage) was *autogenerated* from t02-series.tex with sagetex.sty version 2015/08/26 v3.0-92d9f7a.
import sagetex
_st_ = sagetex.SageTeXProcessor('t02-series', version='2015/08/26 v3.0-92d9f7a', version_check=True)
_st_.current_tex_line = _sage_const_35 
_st_.blockbegin()
try:
 var('n')
 __tmp__=var("n"); a = symbolic_expression((-_sage_const_1 )**n/(_sage_const_2 *n - _sage_const_1 )).function(n)
 __tmp__=var("n"); b = symbolic_expression((n+_sage_const_1 )/(n**_sage_const_3 +_sage_const_2 )).function(n)
 __tmp__=var("n"); c = symbolic_expression(_sage_const_3 /(factorial(n))).function(n)
 
 A=[a(i) for i in (ellipsis_iter(_sage_const_1 ,Ellipsis,_sage_const_6 ))]
 B=[b(i) for i in (ellipsis_iter(_sage_const_1 ,Ellipsis,_sage_const_6 ))]
 C=[c(i) for i in (ellipsis_iter(_sage_const_1 ,Ellipsis,_sage_const_6 ))]
 D=[sum(_sage_const_1 /j**_sage_const_2  for j in range(_sage_const_1 ,n+_sage_const_1 )) for n in (ellipsis_iter(_sage_const_1 ,Ellipsis,_sage_const_6 ))]
except:
 _st_.goboom(_sage_const_45 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_52 
 _st_.inline(_sage_const_0 , latex(D[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_52 )
try:
 _st_.current_tex_line = _sage_const_52 
 _st_.inline(_sage_const_1 , latex(D[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_52 )
try:
 _st_.current_tex_line = _sage_const_52 
 _st_.inline(_sage_const_2 , latex(D[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_52 )
try:
 _st_.current_tex_line = _sage_const_52 
 _st_.inline(_sage_const_3 , latex(D[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_52 )
try:
 _st_.current_tex_line = _sage_const_52 
 _st_.inline(_sage_const_4 , latex(D[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_52 )
try:
 _st_.current_tex_line = _sage_const_52 
 _st_.inline(_sage_const_5 , latex(D[_sage_const_5 ]))
except:
 _st_.goboom(_sage_const_52 )
_st_.current_tex_line = _sage_const_105 
_st_.blockbegin()
try:
 var('n')
 a = sum(_sage_const_2 /_sage_const_3  * (_sage_const_1 /_sage_const_3 )**(n+_sage_const_1 ),n,_sage_const_1 ,oo)
 b = sum(_sage_const_3  * (_sage_const_1 /_sage_const_2 )**(n),n,_sage_const_1 ,oo)
except:
 _st_.goboom(_sage_const_109 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_113 
 _st_.inline(_sage_const_6 , latex(a))
except:
 _st_.goboom(_sage_const_113 )
try:
 _st_.current_tex_line = _sage_const_113 
 _st_.inline(_sage_const_7 , latex(b))
except:
 _st_.goboom(_sage_const_113 )
_st_.current_tex_line = _sage_const_118 
_st_.blockbegin()
try:
 var('n')
 a = sum(_sage_const_1234 /(_sage_const_10000 **n),n,_sage_const_1 ,oo)
except:
 _st_.goboom(_sage_const_121 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_127 
 _st_.inline(_sage_const_8 , latex(a))
except:
 _st_.goboom(_sage_const_127 )
_st_.current_tex_line = _sage_const_210 
_st_.blockbegin()
try:
 var('n')
 __tmp__=var("n"); a = symbolic_expression((_sage_const_9 *n**_sage_const_2 +_sage_const_33 *n+_sage_const_12 )/((n+_sage_const_4 )*(n+_sage_const_3 )*(n+_sage_const_1 )*n)).function(n)
 __tmp__=var("n"); b = symbolic_expression(_sage_const_8 /(n**_sage_const_2 +_sage_const_6 *n+_sage_const_5 )).function(n)
 __tmp__=var("n"); c = symbolic_expression(_sage_const_9 /(n**_sage_const_2 +n - _sage_const_2 )).function(n)
 __tmp__=var("n"); d = symbolic_expression((_sage_const_11  - n)/(n**_sage_const_2 +_sage_const_6 *n+_sage_const_5 )).function(n)
except:
 _st_.goboom(_sage_const_216 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_225 
 _st_.inline(_sage_const_9 , latex(a(n).partial_fraction(n)))
except:
 _st_.goboom(_sage_const_225 )
try:
 _st_.current_tex_line = _sage_const_225 
 _st_.inline(_sage_const_10 , latex(sum(a(n),n,_sage_const_1 ,oo)))
except:
 _st_.goboom(_sage_const_225 )
try:
 _st_.current_tex_line = _sage_const_232 
 _st_.inline(_sage_const_11 , latex(b(n).partial_fraction(n)))
except:
 _st_.goboom(_sage_const_232 )
try:
 _st_.current_tex_line = _sage_const_232 
 _st_.inline(_sage_const_12 , latex(sum(b(n),n,_sage_const_1 ,oo)))
except:
 _st_.goboom(_sage_const_232 )
try:
 _st_.current_tex_line = _sage_const_239 
 _st_.inline(_sage_const_13 , latex(c(n).partial_fraction(n)))
except:
 _st_.goboom(_sage_const_239 )
try:
 _st_.current_tex_line = _sage_const_239 
 _st_.inline(_sage_const_14 , latex(sum(c(n),n,_sage_const_2 ,oo)))
except:
 _st_.goboom(_sage_const_239 )
try:
 _st_.current_tex_line = _sage_const_249 
 _st_.inline(_sage_const_15 , latex(d(n).partial_fraction(n)))
except:
 _st_.goboom(_sage_const_249 )
_st_.endofdoc()

