## -*- encoding: utf-8 -*-
## This file (t02-series.sagetex.sage) was *autogenerated* from t02-series.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('t02-series', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = 35
_st_.blockbegin()
try:
 var('n')
 a(n) = (-1)^n/(2*n - 1)
 b(n) = (n+1)/(n^3+2)
 c(n) = 3/(factorial(n))
 
 A=[a(i) for i in (1..6)]
 B=[b(i) for i in (1..6)]
 C=[c(i) for i in (1..6)]
 D=[sum(1/j^2 for j in range(1,n+1)) for n in (1..6)]
except:
 _st_.goboom(45)
_st_.blockend()
_st_.current_tex_line = 105
_st_.blockbegin()
try:
 var('n')
 a = sum(2/3 * (1/3)^(n+1),n,1,oo)
 b = sum(3 * (1/2)^(n),n,1,oo)
except:
 _st_.goboom(109)
_st_.blockend()
_st_.current_tex_line = 118
_st_.blockbegin()
try:
 var('n')
 a = sum(1234/(10000^n),n,1,oo)
except:
 _st_.goboom(121)
_st_.blockend()
_st_.current_tex_line = 210
_st_.blockbegin()
try:
 var('n')
 a(n) = (9*n^2+33*n+12)/((n+4)*(n+3)*(n+1)*n)
 b(n) = 8/(n^2+6*n+5)
 c(n) = 9/(n^2+n - 2)
 d(n) = (11 - n)/(n^2+6*n+5)
except:
 _st_.goboom(216)
_st_.blockend()
_st_.endofdoc()
