## -*- encoding: utf-8 -*-
## This file (t03-functions.sagetex.sage) was *autogenerated* from t03-functions.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('t03-functions', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = 177
_st_.blockbegin()
try:
 var('x')
 f(x) = -2*x-3
 g(x)=x^2+3*x+1
 h(x)=x/2
except:
 _st_.goboom(182)
_st_.blockend()
_st_.endofdoc()
