## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file t03-functions.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_92 = Integer(92); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_1p4 = RealNumber('1.4'); _sage_const_1p6 = RealNumber('1.6'); _sage_const_121 = Integer(121); _sage_const_0p1 = RealNumber('0.1'); _sage_const_4 = Integer(4); _sage_const_177 = Integer(177); _sage_const_182 = Integer(182); _sage_const_192 = Integer(192)## This file (t03-functions.sagetex.sage) was *autogenerated* from t03-functions.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('t03-functions', version='2021/10/16 v3.6', version_check=True)
try:
 _st_.current_tex_line = _sage_const_92 
 _st_.plot(_sage_const_0 , format='notprovided', _p_=plot((x**_sage_const_2 +_sage_const_1 )/(_sage_const_2 *x - _sage_const_3 ), (x,-_sage_const_5 ,_sage_const_1p4 ), color='black'))
except:
 _st_.goboom(_sage_const_92 )
try:
 _st_.current_tex_line = _sage_const_92 
 _st_.plot(_sage_const_1 , format='notprovided', _p_=plot((x**_sage_const_2 +_sage_const_1 )/(_sage_const_2 *x - _sage_const_3 ), (x,_sage_const_1p6 ,_sage_const_5 ), color='black'))
except:
 _st_.goboom(_sage_const_92 )
try:
 _st_.current_tex_line = _sage_const_92 
 _st_.plot(_sage_const_2 , format='notprovided', _p_=plot(x**_sage_const_2  - _sage_const_3 *x -_sage_const_1 , (x,-_sage_const_5 ,_sage_const_5 ), color='black'))
except:
 _st_.goboom(_sage_const_92 )
try:
 _st_.current_tex_line = _sage_const_121 
 _st_.plot(_sage_const_3 , format='notprovided', _p_=plot(tan(x), (x,-pi/_sage_const_2 +_sage_const_0p1 ,pi/_sage_const_2  - _sage_const_0p1 ), color='black', ticks=pi/_sage_const_4 , tick_formatter=pi))
except:
 _st_.goboom(_sage_const_121 )
_st_.current_tex_line = _sage_const_177 
_st_.blockbegin()
try:
 var('x')
 __tmp__=var("x"); f = symbolic_expression(-_sage_const_2 *x-_sage_const_3 ).function(x)
 __tmp__=var("x"); g = symbolic_expression(x**_sage_const_2 +_sage_const_3 *x+_sage_const_1 ).function(x)
 __tmp__=var("x"); h = symbolic_expression(x/_sage_const_2 ).function(x)
except:
 _st_.goboom(_sage_const_182 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_192 
 _st_.inline(_sage_const_0 , latex(f(g(h(x)))))
except:
 _st_.goboom(_sage_const_192 )
try:
 _st_.current_tex_line = _sage_const_192 
 _st_.inline(_sage_const_1 , latex(expand(g(f(h(x))))))
except:
 _st_.goboom(_sage_const_192 )
try:
 _st_.current_tex_line = _sage_const_192 
 _st_.inline(_sage_const_2 , latex(expand(h(g(f(x))))))
except:
 _st_.goboom(_sage_const_192 )
try:
 _st_.current_tex_line = _sage_const_192 
 _st_.inline(_sage_const_3 , latex(expand(f(f(x)))))
except:
 _st_.goboom(_sage_const_192 )
try:
 _st_.current_tex_line = _sage_const_192 
 _st_.inline(_sage_const_4 , latex(expand(g(g(x)))))
except:
 _st_.goboom(_sage_const_192 )
try:
 _st_.current_tex_line = _sage_const_192 
 _st_.inline(_sage_const_5 , latex(expand(h(h(x)))))
except:
 _st_.goboom(_sage_const_192 )
try:
 _st_.current_tex_line = _sage_const_192 
 _st_.inline(_sage_const_0 , latex(f(g(h(x)))))
except:
 _st_.goboom(_sage_const_192 )
try:
 _st_.current_tex_line = _sage_const_192 
 _st_.inline(_sage_const_1 , latex(expand(g(f(h(x))))))
except:
 _st_.goboom(_sage_const_192 )
try:
 _st_.current_tex_line = _sage_const_192 
 _st_.inline(_sage_const_2 , latex(expand(h(g(f(x))))))
except:
 _st_.goboom(_sage_const_192 )
try:
 _st_.current_tex_line = _sage_const_192 
 _st_.inline(_sage_const_3 , latex(expand(f(f(x)))))
except:
 _st_.goboom(_sage_const_192 )
try:
 _st_.current_tex_line = _sage_const_192 
 _st_.inline(_sage_const_4 , latex(expand(g(g(x)))))
except:
 _st_.goboom(_sage_const_192 )
try:
 _st_.current_tex_line = _sage_const_192 
 _st_.inline(_sage_const_5 , latex(expand(h(h(x)))))
except:
 _st_.goboom(_sage_const_192 )
_st_.endofdoc()

