## -*- encoding: utf-8 -*-
## This file (tutorial-sheet-01-sequences.sagetex.sage) was *autogenerated* from tutorial-sheet-01-sequences.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('tutorial-sheet-01-sequences', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = 68
_st_.blockbegin()
try:
 var('n');
 a(n) = 3*n/(n^2+1);
except:
 _st_.goboom(71)
_st_.blockend()
try:
 _st_.current_tex_line = 73
 _st_.inline(0, latex([a(i) for i in (0..4)]))
except:
 _st_.goboom(73)
_st_.current_tex_line = 76
_st_.blockbegin()
try:
 var('n');
 a(n) = 2^n/(2+2^n);
except:
 _st_.goboom(79)
_st_.blockend()
try:
 _st_.current_tex_line = 82
 _st_.inline(1, latex([a(i) for i in (1..5)]))
except:
 _st_.goboom(82)
_st_.current_tex_line = 85
_st_.blockbegin()
try:
 var('n');
 a(n) = (-1)^n/(3*n);
except:
 _st_.goboom(88)
_st_.blockend()
try:
 _st_.current_tex_line = 91
 _st_.inline(2, latex([a(i) for i in (1..5)]))
except:
 _st_.goboom(91)
_st_.current_tex_line = 94
_st_.blockbegin()
try:
 var('n');
 a(n) = (-1)^(n-1)/(2*n);
except:
 _st_.goboom(97)
_st_.blockend()
try:
 _st_.current_tex_line = 100
 _st_.inline(3, latex([a(i) for i in (1..5)]))
except:
 _st_.goboom(100)
_st_.current_tex_line = 103
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==0 or n==1:
         return 1
     else:
         return a(n-1) + a(n-2);
except:
 _st_.goboom(110)
_st_.blockend()
try:
 _st_.current_tex_line = 113
 _st_.inline(4, latex([a(i) for i in (0..4)]))
except:
 _st_.goboom(113)
_st_.current_tex_line = 116
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==1:
         return 3
     else:
         return a(n-1)/(n-1);
except:
 _st_.goboom(123)
_st_.blockend()
try:
 _st_.current_tex_line = 126
 _st_.inline(5, latex([a(i) for i in (1..5)]))
except:
 _st_.goboom(126)
_st_.current_tex_line = 129
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==0:
         return 2
     else:
         return a(n-1)/(1+a(n-1));
except:
 _st_.goboom(136)
_st_.blockend()
try:
 _st_.current_tex_line = 139
 _st_.inline(6, latex([a(i) for i in (0..4)]))
except:
 _st_.goboom(139)
_st_.current_tex_line = 142
_st_.blockbegin()
try:
 var('n');
 def a(n):
     return 3^n/factorial(2*n)
except:
 _st_.goboom(146)
_st_.blockend()
try:
 _st_.current_tex_line = 149
 _st_.inline(7, latex([a(i) for i in (0..4)]))
except:
 _st_.goboom(149)
_st_.current_tex_line = 153
_st_.blockbegin()
try:
 var('n,m');
 a(n) = 3*n/(n^2+1);
except:
 _st_.goboom(156)
_st_.blockend()
try:
 _st_.current_tex_line = 159
 _st_.inline(8, latex(a(2*m+3)))
except:
 _st_.goboom(159)
_st_.current_tex_line = 160
_st_.blockbegin()
try:
 var('n,m');
 a(n) = 2^n/(2+2^n);
except:
 _st_.goboom(163)
_st_.blockend()
try:
 _st_.current_tex_line = 166
 _st_.inline(9, latex(a(2*m+3)))
except:
 _st_.goboom(166)
_st_.current_tex_line = 167
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^n/(3*n);
except:
 _st_.goboom(170)
_st_.blockend()
try:
 _st_.current_tex_line = 173
 _st_.inline(10, latex(a(2*m+3)))
except:
 _st_.goboom(173)
_st_.current_tex_line = 174
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^(n-1)/(2*n);
except:
 _st_.goboom(177)
_st_.blockend()
try:
 _st_.current_tex_line = 180
 _st_.inline(11, latex(a(2*m+3)))
except:
 _st_.goboom(180)
_st_.current_tex_line = 181
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^(n-1)/(2*n);
except:
 _st_.goboom(184)
_st_.blockend()
_st_.current_tex_line = 209
_st_.blockbegin()
try:
 var('n,m');
 a(n) = 3*n/(n^2+1);
except:
 _st_.goboom(212)
_st_.blockend()
try:
 _st_.current_tex_line = 215
 _st_.plot(0, format='notprovided', _p_=list_plot([a(i) for i in (0..50)]))
except:
 _st_.goboom(215)
_st_.current_tex_line = 216
_st_.blockbegin()
try:
 var('n,m');
 a(n) = 2^n/(2+2^n);
except:
 _st_.goboom(219)
_st_.blockend()
try:
 _st_.current_tex_line = 222
 _st_.plot(1, format='notprovided', _p_=list_plot([a(i) for i in (1..50)]))
except:
 _st_.goboom(222)
_st_.current_tex_line = 223
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^n/(3*n);
except:
 _st_.goboom(226)
_st_.blockend()
try:
 _st_.current_tex_line = 229
 _st_.plot(2, format='notprovided', _p_=list_plot([a(i) for i in (1..50)]))
except:
 _st_.goboom(229)
_st_.current_tex_line = 230
_st_.blockbegin()
try:
 var('n,m');
 a(n) = (-1)^(n-1)/(2*n);
except:
 _st_.goboom(233)
_st_.blockend()
try:
 _st_.current_tex_line = 236
 _st_.plot(3, format='notprovided', _p_=list_plot([a(i) for i in (1..50)]))
except:
 _st_.goboom(236)
_st_.current_tex_line = 237
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==0 or n==1:
         return 1
     else:
         return a(n-1) + a(n-2);
except:
 _st_.goboom(244)
_st_.blockend()
try:
 _st_.current_tex_line = 248
 _st_.plot(4, format='notprovided', _p_=list_plot([a(i) for i in (0..10)]))
except:
 _st_.goboom(248)
_st_.current_tex_line = 249
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==1:
         return 3
     else:
         return a(n-1)/(n-1);
except:
 _st_.goboom(256)
_st_.blockend()
try:
 _st_.current_tex_line = 259
 _st_.plot(5, format='notprovided', _p_=list_plot([a(i) for i in (1..15)]))
except:
 _st_.goboom(259)
_st_.current_tex_line = 260
_st_.blockbegin()
try:
 var('n');
 def a(n):
     if n==0:
         return 2
     else:
         return a(n-1)/(1+a(n-1));
except:
 _st_.goboom(267)
_st_.blockend()
try:
 _st_.current_tex_line = 270
 _st_.plot(6, format='notprovided', _p_=list_plot([a(i) for i in (1..10)]))
except:
 _st_.goboom(270)
_st_.current_tex_line = 271
_st_.blockbegin()
try:
 var('n');
 def a(n):
     return 3^n/factorial(2*n)
except:
 _st_.goboom(275)
_st_.blockend()
try:
 _st_.current_tex_line = 278
 _st_.plot(7, format='notprovided', _p_=list_plot([a(i) for i in (1..8)]))
except:
 _st_.goboom(278)
_st_.endofdoc()
