## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file tutorial-sheet-04-differential-calculus.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_182 = Integer(182); _sage_const_0 = Integer(0); _sage_const_210 = Integer(210); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_191 = Integer(191); _sage_const_10 = Integer(10)## This file (tutorial-sheet-04-differential-calculus.sagetex.sage) was *autogenerated* from tutorial-sheet-04-differential-calculus.tex with sagetex.sty version 2019/01/09 v3.3.
import sagetex
_st_ = sagetex.SageTeXProcessor('tutorial-sheet-04-differential-calculus', version='2019/01/09 v3.3', version_check=True)
_st_.current_tex_line = _sage_const_182 
_st_.blockbegin()
try:
 var('t,x,y,z')
 fa=x**_sage_const_5  + _sage_const_3 *x**_sage_const_4  - _sage_const_5 *x**_sage_const_2  + _sage_const_10 
 fb=_sage_const_3 *x**(_sage_const_1 /_sage_const_2 ) - x**(_sage_const_3 /_sage_const_2 ) + _sage_const_2 *x**(-_sage_const_1 /_sage_const_2 )
 fc=sqrt(_sage_const_3 *t)+_sage_const_3 *sqrt(t)
 fd=(_sage_const_2  + _sage_const_5 *y + _sage_const_1 /_sage_const_2  *y**_sage_const_2 )**(_sage_const_1 /_sage_const_2 )
 fe=(z+_sage_const_1 )*sqrt(z**_sage_const_4  - _sage_const_2 *z +_sage_const_2 )
 ff=x / sqrt(_sage_const_1  - _sage_const_4 *x**_sage_const_2 )
 fg = sqrt(_sage_const_1  + sqrt(x))
except:
 _st_.goboom(_sage_const_191 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_210 
 _st_.inline(_sage_const_0 , latex(diff(fa,x)(x)))
except:
 _st_.goboom(_sage_const_210 )
try:
 _st_.current_tex_line = _sage_const_210 
 _st_.inline(_sage_const_1 , latex(diff(fb,x)(x)))
except:
 _st_.goboom(_sage_const_210 )
try:
 _st_.current_tex_line = _sage_const_210 
 _st_.inline(_sage_const_2 , latex(diff(fc,t)(t)))
except:
 _st_.goboom(_sage_const_210 )
try:
 _st_.current_tex_line = _sage_const_210 
 _st_.inline(_sage_const_3 , latex(diff(fd,y)(y)))
except:
 _st_.goboom(_sage_const_210 )
try:
 _st_.current_tex_line = _sage_const_210 
 _st_.inline(_sage_const_4 , latex(diff(fe,z)(z)))
except:
 _st_.goboom(_sage_const_210 )
try:
 _st_.current_tex_line = _sage_const_210 
 _st_.inline(_sage_const_5 , latex(diff(ff,x)(x)))
except:
 _st_.goboom(_sage_const_210 )
try:
 _st_.current_tex_line = _sage_const_210 
 _st_.inline(_sage_const_6 , latex(diff(fg,x)(x)))
except:
 _st_.goboom(_sage_const_210 )
_st_.endofdoc()

