## -*- encoding: utf-8 -*-
## This file (tutorial-sheet-03-functions.sagetex.sage) was *autogenerated* from tutorial-sheet-03-functions.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('tutorial-sheet-03-functions', version='2019/11/14 v3.4', version_check=True)
_st_.current_tex_line = 212
_st_.blockbegin()
try:
 var('x')
 f(x) = -2*x-3
 g(x)=x^2+3*x+1
 h(x)=x/2
except:
 _st_.goboom(217)
_st_.blockend()
_st_.endofdoc()
