## -*- encoding: utf-8 -*-
## This file (tutorial-sheet-02-series.sagetex.sage) was *autogenerated* from tutorial-sheet-02-series.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('tutorial-sheet-02-series', version='2019/11/14 v3.4', version_check=True)
_st_.current_tex_line = 74
_st_.blockbegin()
try:
 var('n')
 a(n) = (-1)^n/(2*n - 1)
 b(n) = (n+1)/(n^3+2)
 c(n) = 3/(factorial(n))
 
 A=[a(i) for i in (1..6)]
 B=[b(i) for i in (1..6)]
 C=[c(i) for i in (1..6)]
 D=[sum(j^(-2) for j in range(1,n+1)) for n in (1..6)]
except:
 _st_.goboom(84)
_st_.blockend()
_st_.current_tex_line = 141
_st_.blockbegin()
try:
 var('n')
 a = sum(2/3 * (1/3)^(n+1),n,1,oo)
 b = sum(3 * (1/2)^(n),n,1,oo)
except:
 _st_.goboom(145)
_st_.blockend()
_st_.current_tex_line = 154
_st_.blockbegin()
try:
 var('n')
 a = sum(1234/(10000^n),n,1,oo)
except:
 _st_.goboom(157)
_st_.blockend()
_st_.current_tex_line = 247
_st_.blockbegin()
try:
 var('n')
 a(n) = (9*n^2+33*n+12)/((n+4)*(n+3)*(n+1)*n)
 b(n) = 8/(n^2+6*n+5)
 c(n) = 9/(n^2+n - 2)
 d(n) = (11 - n)/(n^2+6*n+5)
except:
 _st_.goboom(253)
_st_.blockend()
_st_.endofdoc()
