## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file tutorial-sheet-03-functions.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_212 = Integer(212); _sage_const_1 = Integer(1); _sage_const_217 = Integer(217)## This file (tutorial-sheet-03-functions.sagetex.sage) was *autogenerated* from tutorial-sheet-03-functions.tex with sagetex.sty version 2019/01/09 v3.3.
import sagetex
_st_ = sagetex.SageTeXProcessor('tutorial-sheet-03-functions', version='2019/01/09 v3.3', version_check=True)
_st_.current_tex_line = _sage_const_212 
_st_.blockbegin()
try:
 var('x')
 __tmp__=var("x"); f = symbolic_expression(-_sage_const_2 *x-_sage_const_3 ).function(x)
 __tmp__=var("x"); g = symbolic_expression(x**_sage_const_2 +_sage_const_3 *x+_sage_const_1 ).function(x)
 __tmp__=var("x"); h = symbolic_expression(x/_sage_const_2 ).function(x)
except:
 _st_.goboom(_sage_const_217 )
_st_.blockend()
_st_.endofdoc()

