## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file tutorial-sheet-02-series.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_74 = Integer(74); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_84 = Integer(84); _sage_const_89 = Integer(89); _sage_const_0 = Integer(0); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_141 = Integer(141); _sage_const_145 = Integer(145); _sage_const_149 = Integer(149); _sage_const_7 = Integer(7); _sage_const_154 = Integer(154); _sage_const_1234 = Integer(1234); _sage_const_10000 = Integer(10000); _sage_const_157 = Integer(157); _sage_const_163 = Integer(163); _sage_const_8 = Integer(8); _sage_const_247 = Integer(247); _sage_const_9 = Integer(9); _sage_const_33 = Integer(33); _sage_const_12 = Integer(12); _sage_const_11 = Integer(11); _sage_const_253 = Integer(253); _sage_const_262 = Integer(262); _sage_const_10 = Integer(10); _sage_const_269 = Integer(269); _sage_const_276 = Integer(276); _sage_const_13 = Integer(13); _sage_const_14 = Integer(14); _sage_const_286 = Integer(286); _sage_const_15 = Integer(15)## This file (tutorial-sheet-02-series.sagetex.sage) was *autogenerated* from tutorial-sheet-02-series.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('tutorial-sheet-02-series', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = _sage_const_74 
_st_.blockbegin()
try:
 var('n')
 __tmp__=var("n"); a = symbolic_expression((-_sage_const_1 )**n/(_sage_const_2 *n - _sage_const_1 )).function(n)
 __tmp__=var("n"); b = symbolic_expression((n+_sage_const_1 )/(n**_sage_const_3 +_sage_const_2 )).function(n)
 __tmp__=var("n"); c = symbolic_expression(_sage_const_3 /(factorial(n))).function(n)
 
 A=[a(i) for i in (ellipsis_iter(_sage_const_1 ,Ellipsis,_sage_const_6 ))]
 B=[b(i) for i in (ellipsis_iter(_sage_const_1 ,Ellipsis,_sage_const_6 ))]
 C=[c(i) for i in (ellipsis_iter(_sage_const_1 ,Ellipsis,_sage_const_6 ))]
 D=[sum(j**(-_sage_const_2 ) for j in range(_sage_const_1 ,n+_sage_const_1 )) for n in (ellipsis_iter(_sage_const_1 ,Ellipsis,_sage_const_6 ))]
except:
 _st_.goboom(_sage_const_84 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_0 , latex(D[_sage_const_0 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_1 , latex(D[_sage_const_1 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_2 , latex(D[_sage_const_2 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_3 , latex(D[_sage_const_3 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_4 , latex(D[_sage_const_4 ]))
except:
 _st_.goboom(_sage_const_89 )
try:
 _st_.current_tex_line = _sage_const_89 
 _st_.inline(_sage_const_5 , latex(D[_sage_const_5 ]))
except:
 _st_.goboom(_sage_const_89 )
_st_.current_tex_line = _sage_const_141 
_st_.blockbegin()
try:
 var('n')
 a = sum(_sage_const_2 /_sage_const_3  * (_sage_const_1 /_sage_const_3 )**(n+_sage_const_1 ),n,_sage_const_1 ,oo)
 b = sum(_sage_const_3  * (_sage_const_1 /_sage_const_2 )**(n),n,_sage_const_1 ,oo)
except:
 _st_.goboom(_sage_const_145 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_149 
 _st_.inline(_sage_const_6 , latex(a))
except:
 _st_.goboom(_sage_const_149 )
try:
 _st_.current_tex_line = _sage_const_149 
 _st_.inline(_sage_const_7 , latex(b))
except:
 _st_.goboom(_sage_const_149 )
_st_.current_tex_line = _sage_const_154 
_st_.blockbegin()
try:
 var('n')
 a = sum(_sage_const_1234 /(_sage_const_10000 **n),n,_sage_const_1 ,oo)
except:
 _st_.goboom(_sage_const_157 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_163 
 _st_.inline(_sage_const_8 , latex(a))
except:
 _st_.goboom(_sage_const_163 )
_st_.current_tex_line = _sage_const_247 
_st_.blockbegin()
try:
 var('n')
 __tmp__=var("n"); a = symbolic_expression((_sage_const_9 *n**_sage_const_2 +_sage_const_33 *n+_sage_const_12 )/((n+_sage_const_4 )*(n+_sage_const_3 )*(n+_sage_const_1 )*n)).function(n)
 __tmp__=var("n"); b = symbolic_expression(_sage_const_8 /(n**_sage_const_2 +_sage_const_6 *n+_sage_const_5 )).function(n)
 __tmp__=var("n"); c = symbolic_expression(_sage_const_9 /(n**_sage_const_2 +n - _sage_const_2 )).function(n)
 __tmp__=var("n"); d = symbolic_expression((_sage_const_11  - n)/(n**_sage_const_2 +_sage_const_6 *n+_sage_const_5 )).function(n)
except:
 _st_.goboom(_sage_const_253 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_262 
 _st_.inline(_sage_const_9 , latex(a(n).partial_fraction(n)))
except:
 _st_.goboom(_sage_const_262 )
try:
 _st_.current_tex_line = _sage_const_262 
 _st_.inline(_sage_const_10 , latex(sum(a(n),n,_sage_const_1 ,oo)))
except:
 _st_.goboom(_sage_const_262 )
try:
 _st_.current_tex_line = _sage_const_269 
 _st_.inline(_sage_const_11 , latex(b(n).partial_fraction(n)))
except:
 _st_.goboom(_sage_const_269 )
try:
 _st_.current_tex_line = _sage_const_269 
 _st_.inline(_sage_const_12 , latex(sum(b(n),n,_sage_const_1 ,oo)))
except:
 _st_.goboom(_sage_const_269 )
try:
 _st_.current_tex_line = _sage_const_276 
 _st_.inline(_sage_const_13 , latex(c(n).partial_fraction(n)))
except:
 _st_.goboom(_sage_const_276 )
try:
 _st_.current_tex_line = _sage_const_276 
 _st_.inline(_sage_const_14 , latex(sum(c(n),n,_sage_const_2 ,oo)))
except:
 _st_.goboom(_sage_const_276 )
try:
 _st_.current_tex_line = _sage_const_286 
 _st_.inline(_sage_const_15 , latex(d(n).partial_fraction(n)))
except:
 _st_.goboom(_sage_const_286 )
_st_.endofdoc()

