## -*- encoding: utf-8 -*-
## This file (tutorial-sheet-04-differential-calculus.sagetex.sage) was *autogenerated* from tutorial-sheet-04-differential-calculus.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('tutorial-sheet-04-differential-calculus', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = 182
_st_.blockbegin()
try:
 var('t,x,y,z')
 fa=x^5 + 3*x^4 - 5*x^2 + 10
 fb=3*x^(1/2) - x^(3/2) + 2*x^(-1/2)
 fc=sqrt(3*t)+3*sqrt(t)
 fd=(2 + 5*y + 1/2 *y^2)^(1/2)
 fe=(z+1)*sqrt(z^4 - 2*z +2)
 ff=x / sqrt(1 - 4*x^2)
 fg = sqrt(1 + sqrt(x))
except:
 _st_.goboom(191)
_st_.blockend()
_st_.endofdoc()
